-- Umsetzung des relationalen Modells aus der Normalisierungsaufgabe
-- in PostgreSQL erstmal ohne Constraints

CREATE TABLE kunde (
	kundennummer VARCHAR(4) PRIMARY KEY,	-- INTEGER oder VARCHAR? 
	kundenname	VARCHAR(30) NOT NULL
);


CREATE TABLE bank (
	bankleitzahl INTEGER PRIMARY KEY,	-- INTEGER oder VARCHAR?
	bankname VARCHAR(30) NOT NULL,  -- ohne weitere Constraints
	bankort VARCHAR(50)		-- Nullable
);

CREATE TABLE bankverbindung (
	id_nr BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	kundennummer VARCHAR(4),	-- wie beim Schlüssel
	bankleitzahl INTEGER,		-- wie beim Schlüssel
	kontonummer	INTEGER,			-- INTEGER oder VARCHAR?
	CONSTRAINT fk_kunde FOREIGN KEY (kundennummer) REFERENCES kunde(kundennummer)
			ON DELETE CASCADE,
	CONSTRAINT fk_bank FOREIGN KEY (bankleitzahl) REFERENCES bank(bankleitzahl)
);


/*******************************************************************************
 Jetzt mit zusätzlichen Check-Constraints inklusive reguläre Ausdrücke.
*****************************************************************************/

ALTER TABLE kunde 
	-- regulärer Ausdruck: Nummer besteht aus genau vier Ziffern
	ADD CONSTRAINT knummer_check CHECK (REGEXP_LIKE(kundennummer, '^[[:digit:]]{4}$'))
;
	
ALTER TABLE kunde
	-- regulärer Ausdruck: Name besteht nur aus (mindestens 2) Buchstaben, der erste groß, Rest klein
	ADD CONSTRAINT kname_check CHECK (REGEXP_LIKE(kundenname, '^[[:upper:]][[:lower:]]{1,}$'))
;


ALTER TABLE bank 
	ADD CONSTRAINT blz_check CHECK (bankleitzahl BETWEEN 10_000_000 AND 99_999_999)
;


CREATE TABLE bankverbindung (
	id_nr BIGINT AUTO_INCREMENT PRIMARY KEY,
	kundennummer CHAR(4),
	bankleitzahl INTEGER UNSIGNED,
	kontonummer	INTEGER UNSIGNED,
	CONSTRAINT fk_kunde FOREIGN KEY (kundennummer) REFERENCES kunde(kundennummer)
			ON DELETE CASCADE,
	CONSTRAINT fk_bank FOREIGN KEY (bankleitzahl) REFERENCES bank(bankleitzahl)
);
	
	
/***********************************************
-- Beispielsdaten einfügen
***********************************************/

INSERT INTO kunde
	VALUES	('0019', 'Huber'),
				('0022', 'Maier'),
				('0033', 'Kaiser'),
				('0037', 'Rein'),
				('5555', 'Karrer');
				
				
INSERT INTO bank
	VALUES	(64240071, 'Commerzbank', 'Rottweil'),
				(66069617, 'Raiffeissenbank', 'Schwenningen'),
				(69470039, 'BW-Bank', 'Villingen'),
				(69470040, 'Deutsche Bank', 'Villingen-Schwenningen');

				
INSERT INTO bank
	VALUES	(64450288, 'Magic Bank', 'Magic Ort');

				
INSERT INTO bankverbindung(kundennummer, bankleitzahl, kontonummer)
	VALUES	('0019', 64240071, 3418505),
				('0019', 64450288, 5655742),
				('0022', 66069617, 85664785),
				('0033', 69470039, 657885547),
				('0037', 64450288, 5688714),
				('5555', 69470039, 100345);
				
		
